### ISSUE TITLE
Setup from image: use USB stick only (no CD needed)

### ISSUE THREAD

**Issue by ipa-fmw** [ipa320/setup_cob4#110]
currently the installation process requires a CD Rom directory to be mounted. Should be fixed by only using a USB Stick based image

**Comment by ipa-fxm** [comment]
@ipa-fmw 
this is fixed? please close if yes

**Comment by ipa-fmw** [comment]
no, this is not fixed. As we have netboot now this is not that important any more... Let's keep open but move down in our priority list.
